name:                haskell-tdlib
version:             2.0.46.0
github:              "mejgun/haskell-tdlib"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mejgun/haskell-tdlib>


language: GHC2021

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- time
- unordered-containers
- text
- containers
- base64-bytestring
- hashable

default-extensions:
- OverloadedStrings

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wno-partial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  extra-libraries: tdjson

executables:
  haskell-tdlib-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -W
    - -Wall
    - -Werror
    dependencies:
    - haskell-tdlib
    default-extensions:
    - DuplicateRecordFields
    - NoFieldSelectors

tests:
  haskell-tdlib-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-tdlib
