-- GENERATED

module API.ChatStatisticsMessageInteractionCounters where

import Data.Aeson.Types

data ChatStatisticsMessageInteractionCounters

instance ToJSON ChatStatisticsMessageInteractionCounters

instance FromJSON ChatStatisticsMessageInteractionCounters

instance Show ChatStatisticsMessageInteractionCounters

