-- GENERATED
module API.EmailAddressAuthenticationCodeInfo where

import Data.Aeson.Types

data EmailAddressAuthenticationCodeInfo

instance Eq EmailAddressAuthenticationCodeInfo

instance ToJSON EmailAddressAuthenticationCodeInfo

instance FromJSON EmailAddressAuthenticationCodeInfo

instance Show EmailAddressAuthenticationCodeInfo

