-- GENERATED
module API.PhoneNumberAuthenticationSettings where

import Data.Aeson.Types

data PhoneNumberAuthenticationSettings

instance Eq PhoneNumberAuthenticationSettings

instance ToJSON PhoneNumberAuthenticationSettings

instance FromJSON PhoneNumberAuthenticationSettings

instance Show PhoneNumberAuthenticationSettings

