-- GENERATED
module API.Functions.CheckEmailAddressVerificationCode where

import Data.Aeson.Types

data CheckEmailAddressVerificationCode

instance Eq CheckEmailAddressVerificationCode

instance ToJSON CheckEmailAddressVerificationCode

instance FromJSON CheckEmailAddressVerificationCode

instance Show CheckEmailAddressVerificationCode

