-- GENERATED
module API.Functions.GetChatNotificationSettingsExceptions where

import Data.Aeson.Types

data GetChatNotificationSettingsExceptions

instance Eq GetChatNotificationSettingsExceptions

instance ToJSON GetChatNotificationSettingsExceptions

instance FromJSON GetChatNotificationSettingsExceptions

instance Show GetChatNotificationSettingsExceptions

