-- GENERATED
module API.Functions.GetPassportAuthorizationFormAvailableElements where

import Data.Aeson.Types

data GetPassportAuthorizationFormAvailableElements

instance Eq GetPassportAuthorizationFormAvailableElements

instance ToJSON GetPassportAuthorizationFormAvailableElements

instance FromJSON GetPassportAuthorizationFormAvailableElements

instance Show GetPassportAuthorizationFormAvailableElements

