-- GENERATED

module API.Functions.GetPassportAuthorizationFormAvailableElements where

import Data.Aeson.Types

data GetPassportAuthorizationFormAvailableElements

instance ToJSON GetPassportAuthorizationFormAvailableElements

instance FromJSON GetPassportAuthorizationFormAvailableElements

