-- GENERATED
module API.Functions.ResendEmailAddressVerificationCode where

import Data.Aeson.Types

data ResendEmailAddressVerificationCode

instance Eq ResendEmailAddressVerificationCode

instance ToJSON ResendEmailAddressVerificationCode

instance FromJSON ResendEmailAddressVerificationCode

instance Show ResendEmailAddressVerificationCode

