-- GENERATED
module API.Functions.ResendPhoneNumberVerificationCode where

import Data.Aeson.Types

data ResendPhoneNumberVerificationCode

instance Eq ResendPhoneNumberVerificationCode

instance ToJSON ResendPhoneNumberVerificationCode

instance FromJSON ResendPhoneNumberVerificationCode

instance Show ResendPhoneNumberVerificationCode

