-- GENERATED
module API.Functions.SendChatScreenshotTakenNotification where

import Data.Aeson.Types

data SendChatScreenshotTakenNotification

instance Eq SendChatScreenshotTakenNotification

instance ToJSON SendChatScreenshotTakenNotification

instance FromJSON SendChatScreenshotTakenNotification

instance Show SendChatScreenshotTakenNotification

