-- GENERATED
module API.Functions.SetDefaultGroupAdministratorRights where

import Data.Aeson.Types

data SetDefaultGroupAdministratorRights

instance Eq SetDefaultGroupAdministratorRights

instance ToJSON SetDefaultGroupAdministratorRights

instance FromJSON SetDefaultGroupAdministratorRights

instance Show SetDefaultGroupAdministratorRights

