-- GENERATED
module API.Functions.SetGroupCallParticipantIsSpeaking where

import Data.Aeson.Types

data SetGroupCallParticipantIsSpeaking

instance Eq SetGroupCallParticipantIsSpeaking

instance ToJSON SetGroupCallParticipantIsSpeaking

instance FromJSON SetGroupCallParticipantIsSpeaking

instance Show SetGroupCallParticipantIsSpeaking

