-- GENERATED
module API.Functions.ToggleSupergroupIsAllHistoryAvailable where

import Data.Aeson.Types

data ToggleSupergroupIsAllHistoryAvailable

instance Eq ToggleSupergroupIsAllHistoryAvailable

instance ToJSON ToggleSupergroupIsAllHistoryAvailable

instance FromJSON ToggleSupergroupIsAllHistoryAvailable

instance Show ToggleSupergroupIsAllHistoryAvailable

