-- GENERATED
module API.Functions.ToggleChatDefaultDisableNotification where

import Data.Aeson.Types

data ToggleChatDefaultDisableNotification

instance Eq ToggleChatDefaultDisableNotification

instance ToJSON ToggleChatDefaultDisableNotification

instance FromJSON ToggleChatDefaultDisableNotification

instance Show ToggleChatDefaultDisableNotification

