-- GENERATED
module API.Functions.UpgradeBasicGroupChatToSupergroupChat where

import Data.Aeson.Types

data UpgradeBasicGroupChatToSupergroupChat

instance Eq UpgradeBasicGroupChatToSupergroupChat

instance ToJSON UpgradeBasicGroupChatToSupergroupChat

instance FromJSON UpgradeBasicGroupChatToSupergroupChat

instance Show UpgradeBasicGroupChatToSupergroupChat

